# Generated by Django 5.2.8 on 2025-12-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_shippingfee_taxrate_cart_order_teaproduct_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritetea',
            options={'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り一覧'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterUniqueTogether(
            name='favoritetea',
            unique_together={('user', 'tea')},
        ),
    ]
