# Generated by Django 5.2.8 on 2025-12-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_favoritetea_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={'verbose_name': 'お茶', 'verbose_name_plural': 'お茶一覧'},
        ),
    ]
