# Generated by Django 5.2.8 on 2025-12-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_tea_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tea_preference',
            field=models.CharField(blank=True, choices=[('light', '浅蒸し'), ('middle', '中蒸し'), ('deep', '深蒸し')], help_text='診断結果によるお茶の好み（蒸し度）', max_length=20, null=True, verbose_name='お茶の好み'),
        ),
    ]
